/**
 * markdown-report.ts — D6: Explainable Markdown Report Generator
 *
 * Generates the single human-readable document that appears in every Locus PR body.
 * It is the ONE place a reviewing engineer sees the full picture:
 *  - Old locator → new locator
 *  - Classification reasoning
 *  - Confidence score + band label
 *  - Degraded-input warnings (amber notes)
 *  - Running heal count for this element
 *  - Rewriter outcome (patched / validation-failed / locator-not-found)
 *  - Candidate evaluation table (all resolver candidates + gate results)
 *
 * For degraded cases (missing DOM / diff / screenshot), the report describes
 * exactly what was missing and how it affected confidence.
 */

import type {
  FailureEvent,
  ClassificationResult,
  ResolverResult,
} from '../types/shared-types';
import type { RewriteResult } from '../rewriter/pom-rewriter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ReportInput {
  event: FailureEvent;
  classificationResult: ClassificationResult;
  resolverResult: ResolverResult | null; // null if resolver was not invoked
  rewriteResult: RewriteResult | null;   // null if rewriter was not reached
  healCount: number;
  isRevert?: boolean;
}

// ---------------------------------------------------------------------------
// Band label formatting
// ---------------------------------------------------------------------------

const BAND_LABELS: Record<string, string> = {
  'below-60': '🔴 BELOW THRESHOLD (<60%) — Human review required',
  'amber-60-79': '🟡 AMBER (60–79%) — Explicit approval comment required before merge',
  'warning-80-94': '🟠 CONFIDENCE WARNING (80–94%) — Healing with caution note',
  'high-95-100': '🟢 HIGH CONFIDENCE (95–100%) — Auto-labelled as reliable fix',
};

const CLASSIFICATION_BADGES: Record<string, string> = {
  'real-bug': '🔴 **Real Bug**',
  'ui-drift': '🔵 **UI Drift**',
  'flakiness': '⚡ **Flakiness**',
};

const ACTION_DESCRIPTIONS: Record<string, string> = {
  'skip-human-review': 'Healing skipped — flagged for human review',
  'fail-loudly': '🚨 Build failed loudly — genuine application bug detected',
  'amber-pr-requires-approval': '⚠️ Amber PR raised — requires an explicit approval comment before merge',
  'heal-with-warning': '🔧 Locator healed with confidence warning',
  'standard-heal-auto-label': '✅ Locator healed — PR auto-labelled `locus:high-confidence`',
  'retry-annotation': '⚡ Healing skipped — flaky test, retry annotation suggested',
};

// ---------------------------------------------------------------------------
// Candidate table builder
// ---------------------------------------------------------------------------

function buildCandidateTable(resolverResult: ResolverResult): string {
  if (resolverResult.allCandidates.length === 0) {
    return '_No candidates were generated by the resolver._';
  }

  const header = '| Strategy | Locator | Exists | Unique | Semantic Match | Accepted |';
  const divider = '|---|---|:---:|:---:|:---:|:---:|';
  const rows = resolverResult.allCandidates.map((c) => {
    const accepted = c.accepted ? '✅ Yes' : '❌ No';
    const exists = c.gates.existence ? '✅' : '❌';
    const unique = c.gates.uniqueness ? '✅' : '❌';
    const semantic = c.gates.semanticIdentity ? '✅' : '❌';
    return `| \`${c.strategy}\` | \`${c.locator}\` | ${exists} | ${unique} | ${semantic} | ${accepted} |`;
  });

  return [header, divider, ...rows].join('\n');
}

// ---------------------------------------------------------------------------
// Main report generator
// ---------------------------------------------------------------------------

/**
 * Build the full markdown report for a Locus PR or PR comment.
 *
 * @param input — All pipeline outputs gathered by the orchestrator.
 * @returns A markdown string ready to use as a GitHub PR body or comment.
 */
export function generateMarkdownReport(input: ReportInput): string {
  const { event, classificationResult, resolverResult, rewriteResult, healCount, isRevert } =
    input;

  const bandLabel = BAND_LABELS[classificationResult.confidenceBand] ?? classificationResult.confidenceBand;
  const classificationBadge =
    CLASSIFICATION_BADGES[classificationResult.classification] ?? classificationResult.classification;
  const actionDescription =
    ACTION_DESCRIPTIONS[classificationResult.action] ?? classificationResult.action;

  const lines: string[] = [];

  // ── Header ───────────────────────────────────────────────────────────────
  if (isRevert) {
    lines.push('# 🔄 Locus Auto-Revert');
    lines.push('');
    lines.push(
      '> **Heal attempt failed on re-run. Reverting to original locator.**  ',
      '> This element has been marked **unresolvable** in Firestore until a human clears it.',
    );
  } else {
    lines.push('# 🩹 Locus Healing Report');
  }

  lines.push('');
  lines.push(`**Test:** \`${event.testName}\`  `);
  lines.push(`**Element ID:** \`${event.elementId}\`  `);
  lines.push(`**POM File:** \`${event.pomFilePath}\`  `);
  lines.push(`**Heal Attempt #${healCount}** for this element  `);
  lines.push(`**Triggered by CI Run:** \`${event.githubRunId}\`  `);
  if (event.githubPrNumber) {
    lines.push(`**Source PR:** #${event.githubPrNumber}  `);
  }
  lines.push(`**Timestamp:** ${event.timestamp.toISOString()}  `);
  lines.push('');

  // ── Data quality warnings ─────────────────────────────────────────────────
  if (event.degradedWarnings.length > 0) {
    lines.push('---');
    lines.push('## ⚠️ Degraded Input Warnings');
    lines.push('');
    lines.push(
      'The following inputs were missing or unavailable when this failure was processed. ' +
        'Each affects confidence as described.',
    );
    lines.push('');
    for (const w of event.degradedWarnings) {
      lines.push(`### Missing: \`${w.field}\``);
      lines.push(`- **Reason:** ${w.reason}`);
      lines.push(`- **Impact on confidence:** ${w.impactOnConfidence}`);
      lines.push('');
    }
  }

  // ── Classification ────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('## 🤖 Classifier Result');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Classification | ${classificationBadge} |`);
  lines.push(`| Confidence | **${classificationResult.confidence}%** |`);
  lines.push(`| Confidence Band | ${bandLabel} |`);
  lines.push(`| Action | ${actionDescription} |`);
  lines.push('');
  lines.push('**Reasoning from classifier:**');
  lines.push('');
  lines.push(`> ${classificationResult.reasoning}`);
  lines.push('');

  // ── Locator change ────────────────────────────────────────────────────────
  if (resolverResult?.acceptedCandidate) {
    lines.push('---');
    lines.push('## 🔧 Locator Change');
    lines.push('');
    lines.push('| | Locator |');
    lines.push('|---|---|');
    lines.push(`| **Old (broken)** | \`${event.oldLocator}\` |`);
    lines.push(`| **New (healed)** | \`${resolverResult.acceptedCandidate.locator}\` |`);
    lines.push(`| **Strategy** | \`${resolverResult.acceptedCandidate.strategy}\` |`);
    lines.push('');
  }

  // ── Resolver candidates ───────────────────────────────────────────────────
  if (resolverResult) {
    lines.push('---');
    lines.push('## 🔍 Resolver Candidate Evaluation');
    lines.push('');
    if (resolverResult.unresolvable) {
      lines.push('> ❌ **Unresolvable** — all candidate strategies failed validation gates.');
      lines.push('');
      if (resolverResult.failureReason) {
        lines.push(`**Reason:** ${resolverResult.failureReason}`);
        lines.push('');
      }
    }
    lines.push(buildCandidateTable(resolverResult));
    lines.push('');
    lines.push(
      '_Gate definitions: **Exists** = found in captured DOM; **Unique** = matches exactly one element;_ ',
      '_**Semantic Match** = role and accessible name match the original element._',
    );
    lines.push('');
  } else if (classificationResult.shouldInvokeResolver === false) {
    lines.push('---');
    lines.push('## 🔍 Resolver');
    lines.push('');
    lines.push(
      '_Resolver was not invoked. This is expected for real-bug / flakiness classifications ' +
        `or confidence below ${60}% — cost gate prevents unnecessary resolver calls._`,
    );
    lines.push('');
  }

  // ── Rewriter result ───────────────────────────────────────────────────────
  if (rewriteResult) {
    lines.push('---');
    lines.push('## 📝 POM Patch Result');
    lines.push('');
    lines.push(`**Status:** \`${rewriteResult.status}\`  `);
    lines.push('');
    lines.push(rewriteResult.explanation);
    lines.push('');
    if (rewriteResult.rawSuggestion) {
      lines.push('**Raw locator suggestion (apply manually):**');
      lines.push('```');
      lines.push(rewriteResult.rawSuggestion);
      lines.push('```');
      lines.push('');
    }
  }

  // ── Next steps ───────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('## ✅ Next Steps for Reviewer');
  lines.push('');

  const band = classificationResult.confidenceBand;
  if (band === 'amber-60-79') {
    lines.push(
      '1. Review the locator change and classifier reasoning above carefully.',
      '2. **Leave an explicit approval comment** (e.g., "locus: approved") before merging.',
      '   Merging without an explicit approval comment is a policy violation for amber PRs.',
      '3. After merging, the CI post-merge run will re-run the healed test automatically.',
      '4. If the post-merge run fails, Locus will auto-raise a revert PR.',
    );
  } else if (band === 'warning-80-94') {
    lines.push(
      '1. Review the locator change and the confidence warning note above.',
      '2. Merge via the GitHub web UI when satisfied.',
      '3. Post-merge CI will re-run the healed test automatically.',
    );
  } else if (band === 'high-95-100') {
    lines.push(
      '1. Review the locator change — this PR is auto-labelled `locus:high-confidence`.',
      '2. Merge via the GitHub web UI when satisfied.',
      '3. Post-merge CI will re-run the healed test automatically.',
    );
  } else if (resolverResult?.unresolvable) {
    lines.push(
      '1. Review the attached DOM context and all resolver candidates.',
      '2. Apply the locator fix manually (raw suggestion above, if available).',
      '3. If the element has been removed, update the test accordingly.',
    );
  }

  lines.push('');
  lines.push('---');
  lines.push('_Report generated by [Locus](https://github.com/locus-self-healing) — Post-execution Playwright self-healing tool._');

  return lines.join('\n');
}
